---
# tasks file for groups
  - name: Add group
    community.aws.iam:
      iam_type: group
      name: "DevOps"
      state: present

  - name: Add users
    community.aws.iam:
      iam_type: user
      name: "{{ item }}"
      state: present
      password: "8$av`-U{FtYA\N4f,Qc:"
      access_key_state: create
    loop:
    - my_ansible_user1
    - my_ansible_user2