---
# tasks file for php
  - name: install packages
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - php
      - php-mysql